on: [pull_request]

name: connect

jobs:
    php-cs:
        name: Coding style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
            - name: php-cs-fixer
              run: |
                  wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.90.0/php-cs-fixer.phar -q
                  php php-cs-fixer.phar fix --dry-run --diff

    php-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: ['8.0', '8.1', '8.2', '8.3', '8.4']
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: none
                  tools: symfony-cli

            - name: Get Composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Mount PHP dependencies cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('console/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install PHP dependencies
              run: |
                composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-scripts

            - name: PHPUnit
              run: ./vendor/bin/simple-phpunit
